version: "3"
services:
  database:
    image: mariadb:latest
    restart: always
    ports:
      - "59487:3306"
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - db.env
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
