version: "3"
services:
  app:
    build: .
    container_name: yue
    stdin_open: true
    tty: true
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./logs:/var/log/yue
      - ./temp:/app/temp
      - ./tsconfig.json:/app/tsconfig.json
      - ./tslint.json:/app/tslint.json
    depends_on:
      - database
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
