version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: yue
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./tests:/app/tests
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./logs:/var/log/yue
      - ./tsconfig.json:/app/tsconfig.json
      - ./.eslintrc.cjs:/app/.eslintrc.cjs
      - ./jest.config.cjs:/app/jest.config.cjs
    env_file:
      - bot.env
    depends_on:
      - database
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
