version: "3"
services:
  app:
    build:
      context: .
      dockerfile: prod.dockerfile
    container_name: yue
    volumes:
      - ./logs:/var/log/yue
    env_file:
      - bot.env
    depends_on:
      - database
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
